#!/usr/bin/env python3
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'social_media_api.settings')
django.setup()

print("MANUAL TEST INSTRUCTIONS FOR STEP 5")
print("=" * 60)
print("\nTo test the likes and notifications features manually:")
print("\n1. Start the Django server:")
print("   python manage.py runserver")
print("\n2. Use the following endpoints with a tool like Postman or curl:")
print("\n   LIKE A POST:")
print("   POST http://127.0.0.1:8000/api/posts/{post_id}/like/")
print("   Headers: Authorization: Token {your_token}")
print("\n   UNLIKE A POST:")
print("   DELETE http://127.0.0.1:8000/api/posts/{post_id}/unlike/")
print("   Headers: Authorization: Token {your_token}")
print("\n   VIEW NOTIFICATIONS:")
print("   GET http://127.0.0.1:8000/api/notifications/")
print("   Headers: Authorization: Token {your_token}")
print("\n   MARK NOTIFICATION AS READ:")
print("   POST http://127.0.0.1:8000/api/notifications/{notification_id}/mark-read/")
print("   Headers: Authorization: Token {your_token}")
print("\n3. Test scenarios to verify:")
print("   - Like a post (should succeed first time)")
print("   - Like same post again (should fail with 400)")
print("   - Unlike the post (should succeed)")
print("   - Unlike a post not liked (should fail with 400)")
print("   - View notifications after being followed/liked/commented")
print("   - Mark notification as read")
print("   - Try to mark other user's notification as read (should fail with 403)")
print("\nStep 5: Testing Complete when all scenarios work correctly ✓")